/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FleetIndexRouteImport } from './routes/fleet/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PoliciesTermsRouteImport } from './routes/policies/terms'
import { Route as PoliciesPrivacyRouteImport } from './routes/policies/privacy'
import { Route as PoliciesCancellationRouteImport } from './routes/policies/cancellation'
import { Route as FleetCarSlugRouteImport } from './routes/fleet/$carSlug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe-webhook'
import { Route as AdminCalendarRouteImport } from './routes/admin/calendar'
import { Route as AuthedProfileRouteImport } from './routes/_authed.profile'
import { Route as AuthedTripsIndexRouteImport } from './routes/_authed.trips.index'
import { Route as ApiCronSyncTuroRouteImport } from './routes/api/cron/sync-turo'
import { Route as ApiCronPaymentsRouteImport } from './routes/api/cron/payments'
import { Route as AdminUserUserIdRouteImport } from './routes/admin/user.$userId'
import { Route as AdminTripsHistoryRouteImport } from './routes/admin/trips/history'
import { Route as AdminTripsBookedRouteImport } from './routes/admin/trips/booked'
import { Route as AdminReservationBookingIdRouteImport } from './routes/admin/reservation.$bookingId'
import { Route as AdminBusinessTaxInformationRouteImport } from './routes/admin/business/tax-information'
import { Route as AdminBusinessRatingsReviewsRouteImport } from './routes/admin/business/ratings-reviews'
import { Route as AdminBusinessEarningsRouteImport } from './routes/admin/business/earnings'
import { Route as AuthedTripsBookingIdRouteImport } from './routes/_authed.trips.$bookingId'
import { Route as AuthedProfileEditRouteImport } from './routes/_authed.profile_.edit'
import { Route as AuthedCheckoutCarIdRouteImport } from './routes/_authed.checkout.$carId'
import { Route as AuthedTripsBookingIdReceiptRouteImport } from './routes/_authed.trips.$bookingId_.receipt'
import { Route as AuthedTripsBookingIdPhotosRouteImport } from './routes/_authed.trips.$bookingId_.photos'
import { Route as AuthedTripsBookingIdExtrasRouteImport } from './routes/_authed.trips.$bookingId_.extras'
import { Route as AuthedTripsBookingIdPayChargeIdRouteImport } from './routes/_authed.trips.$bookingId_.pay.$chargeId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetIndexRoute = FleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PoliciesTermsRoute = PoliciesTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PoliciesRoute,
} as any)
const PoliciesPrivacyRoute = PoliciesPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PoliciesRoute,
} as any)
const PoliciesCancellationRoute = PoliciesCancellationRouteImport.update({
  id: '/cancellation',
  path: '/cancellation',
  getParentRoute: () => PoliciesRoute,
} as any)
const FleetCarSlugRoute = FleetCarSlugRouteImport.update({
  id: '/fleet/$carSlug',
  path: '/fleet/$carSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTripsIndexRoute = AuthedTripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiCronSyncTuroRoute = ApiCronSyncTuroRouteImport.update({
  id: '/api/cron/sync-turo',
  path: '/api/cron/sync-turo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronPaymentsRoute = ApiCronPaymentsRouteImport.update({
  id: '/api/cron/payments',
  path: '/api/cron/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserUserIdRoute = AdminUserUserIdRouteImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTripsHistoryRoute = AdminTripsHistoryRouteImport.update({
  id: '/trips/history',
  path: '/trips/history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTripsBookedRoute = AdminTripsBookedRouteImport.update({
  id: '/trips/booked',
  path: '/trips/booked',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReservationBookingIdRoute =
  AdminReservationBookingIdRouteImport.update({
    id: '/reservation/$bookingId',
    path: '/reservation/$bookingId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBusinessTaxInformationRoute =
  AdminBusinessTaxInformationRouteImport.update({
    id: '/business/tax-information',
    path: '/business/tax-information',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBusinessRatingsReviewsRoute =
  AdminBusinessRatingsReviewsRouteImport.update({
    id: '/business/ratings-reviews',
    path: '/business/ratings-reviews',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBusinessEarningsRoute = AdminBusinessEarningsRouteImport.update({
  id: '/business/earnings',
  path: '/business/earnings',
  getParentRoute: () => AdminRoute,
} as any)
const AuthedTripsBookingIdRoute = AuthedTripsBookingIdRouteImport.update({
  id: '/trips/$bookingId',
  path: '/trips/$bookingId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProfileEditRoute = AuthedProfileEditRouteImport.update({
  id: '/profile_/edit',
  path: '/profile/edit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCheckoutCarIdRoute = AuthedCheckoutCarIdRouteImport.update({
  id: '/checkout/$carId',
  path: '/checkout/$carId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTripsBookingIdReceiptRoute =
  AuthedTripsBookingIdReceiptRouteImport.update({
    id: '/trips/$bookingId_/receipt',
    path: '/trips/$bookingId/receipt',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedTripsBookingIdPhotosRoute =
  AuthedTripsBookingIdPhotosRouteImport.update({
    id: '/trips/$bookingId_/photos',
    path: '/trips/$bookingId/photos',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedTripsBookingIdExtrasRoute =
  AuthedTripsBookingIdExtrasRouteImport.update({
    id: '/trips/$bookingId_/extras',
    path: '/trips/$bookingId/extras',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedTripsBookingIdPayChargeIdRoute =
  AuthedTripsBookingIdPayChargeIdRouteImport.update({
    id: '/trips/$bookingId_/pay/$chargeId',
    path: '/trips/$bookingId/pay/$chargeId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/policies': typeof PoliciesRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/profile': typeof AuthedProfileRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/fleet/$carSlug': typeof FleetCarSlugRoute
  '/policies/cancellation': typeof PoliciesCancellationRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/fleet/': typeof FleetIndexRoute
  '/checkout/$carId': typeof AuthedCheckoutCarIdRoute
  '/profile/edit': typeof AuthedProfileEditRoute
  '/trips/$bookingId': typeof AuthedTripsBookingIdRoute
  '/admin/business/earnings': typeof AdminBusinessEarningsRoute
  '/admin/business/ratings-reviews': typeof AdminBusinessRatingsReviewsRoute
  '/admin/business/tax-information': typeof AdminBusinessTaxInformationRoute
  '/admin/reservation/$bookingId': typeof AdminReservationBookingIdRoute
  '/admin/trips/booked': typeof AdminTripsBookedRoute
  '/admin/trips/history': typeof AdminTripsHistoryRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
  '/api/cron/payments': typeof ApiCronPaymentsRoute
  '/api/cron/sync-turo': typeof ApiCronSyncTuroRoute
  '/trips/': typeof AuthedTripsIndexRoute
  '/trips/$bookingId/extras': typeof AuthedTripsBookingIdExtrasRoute
  '/trips/$bookingId/photos': typeof AuthedTripsBookingIdPhotosRoute
  '/trips/$bookingId/receipt': typeof AuthedTripsBookingIdReceiptRoute
  '/trips/$bookingId/pay/$chargeId': typeof AuthedTripsBookingIdPayChargeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/policies': typeof PoliciesRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/profile': typeof AuthedProfileRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/fleet/$carSlug': typeof FleetCarSlugRoute
  '/policies/cancellation': typeof PoliciesCancellationRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/admin': typeof AdminIndexRoute
  '/fleet': typeof FleetIndexRoute
  '/checkout/$carId': typeof AuthedCheckoutCarIdRoute
  '/profile/edit': typeof AuthedProfileEditRoute
  '/trips/$bookingId': typeof AuthedTripsBookingIdRoute
  '/admin/business/earnings': typeof AdminBusinessEarningsRoute
  '/admin/business/ratings-reviews': typeof AdminBusinessRatingsReviewsRoute
  '/admin/business/tax-information': typeof AdminBusinessTaxInformationRoute
  '/admin/reservation/$bookingId': typeof AdminReservationBookingIdRoute
  '/admin/trips/booked': typeof AdminTripsBookedRoute
  '/admin/trips/history': typeof AdminTripsHistoryRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
  '/api/cron/payments': typeof ApiCronPaymentsRoute
  '/api/cron/sync-turo': typeof ApiCronSyncTuroRoute
  '/trips': typeof AuthedTripsIndexRoute
  '/trips/$bookingId/extras': typeof AuthedTripsBookingIdExtrasRoute
  '/trips/$bookingId/photos': typeof AuthedTripsBookingIdPhotosRoute
  '/trips/$bookingId/receipt': typeof AuthedTripsBookingIdReceiptRoute
  '/trips/$bookingId/pay/$chargeId': typeof AuthedTripsBookingIdPayChargeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/policies': typeof PoliciesRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/fleet/$carSlug': typeof FleetCarSlugRoute
  '/policies/cancellation': typeof PoliciesCancellationRoute
  '/policies/privacy': typeof PoliciesPrivacyRoute
  '/policies/terms': typeof PoliciesTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/fleet/': typeof FleetIndexRoute
  '/_authed/checkout/$carId': typeof AuthedCheckoutCarIdRoute
  '/_authed/profile_/edit': typeof AuthedProfileEditRoute
  '/_authed/trips/$bookingId': typeof AuthedTripsBookingIdRoute
  '/admin/business/earnings': typeof AdminBusinessEarningsRoute
  '/admin/business/ratings-reviews': typeof AdminBusinessRatingsReviewsRoute
  '/admin/business/tax-information': typeof AdminBusinessTaxInformationRoute
  '/admin/reservation/$bookingId': typeof AdminReservationBookingIdRoute
  '/admin/trips/booked': typeof AdminTripsBookedRoute
  '/admin/trips/history': typeof AdminTripsHistoryRoute
  '/admin/user/$userId': typeof AdminUserUserIdRoute
  '/api/cron/payments': typeof ApiCronPaymentsRoute
  '/api/cron/sync-turo': typeof ApiCronSyncTuroRoute
  '/_authed/trips/': typeof AuthedTripsIndexRoute
  '/_authed/trips/$bookingId_/extras': typeof AuthedTripsBookingIdExtrasRoute
  '/_authed/trips/$bookingId_/photos': typeof AuthedTripsBookingIdPhotosRoute
  '/_authed/trips/$bookingId_/receipt': typeof AuthedTripsBookingIdReceiptRoute
  '/_authed/trips/$bookingId_/pay/$chargeId': typeof AuthedTripsBookingIdPayChargeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/login'
    | '/my-bookings'
    | '/policies'
    | '/reviews'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/profile'
    | '/admin/calendar'
    | '/api/stripe-webhook'
    | '/fleet/$carSlug'
    | '/policies/cancellation'
    | '/policies/privacy'
    | '/policies/terms'
    | '/admin/'
    | '/fleet/'
    | '/checkout/$carId'
    | '/profile/edit'
    | '/trips/$bookingId'
    | '/admin/business/earnings'
    | '/admin/business/ratings-reviews'
    | '/admin/business/tax-information'
    | '/admin/reservation/$bookingId'
    | '/admin/trips/booked'
    | '/admin/trips/history'
    | '/admin/user/$userId'
    | '/api/cron/payments'
    | '/api/cron/sync-turo'
    | '/trips/'
    | '/trips/$bookingId/extras'
    | '/trips/$bookingId/photos'
    | '/trips/$bookingId/receipt'
    | '/trips/$bookingId/pay/$chargeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/about'
    | '/contact'
    | '/faq'
    | '/login'
    | '/my-bookings'
    | '/policies'
    | '/reviews'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/profile'
    | '/admin/calendar'
    | '/api/stripe-webhook'
    | '/fleet/$carSlug'
    | '/policies/cancellation'
    | '/policies/privacy'
    | '/policies/terms'
    | '/admin'
    | '/fleet'
    | '/checkout/$carId'
    | '/profile/edit'
    | '/trips/$bookingId'
    | '/admin/business/earnings'
    | '/admin/business/ratings-reviews'
    | '/admin/business/tax-information'
    | '/admin/reservation/$bookingId'
    | '/admin/trips/booked'
    | '/admin/trips/history'
    | '/admin/user/$userId'
    | '/api/cron/payments'
    | '/api/cron/sync-turo'
    | '/trips'
    | '/trips/$bookingId/extras'
    | '/trips/$bookingId/photos'
    | '/trips/$bookingId/receipt'
    | '/trips/$bookingId/pay/$chargeId'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/_authed'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/login'
    | '/my-bookings'
    | '/policies'
    | '/reviews'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authed/profile'
    | '/admin/calendar'
    | '/api/stripe-webhook'
    | '/fleet/$carSlug'
    | '/policies/cancellation'
    | '/policies/privacy'
    | '/policies/terms'
    | '/admin/'
    | '/fleet/'
    | '/_authed/checkout/$carId'
    | '/_authed/profile_/edit'
    | '/_authed/trips/$bookingId'
    | '/admin/business/earnings'
    | '/admin/business/ratings-reviews'
    | '/admin/business/tax-information'
    | '/admin/reservation/$bookingId'
    | '/admin/trips/booked'
    | '/admin/trips/history'
    | '/admin/user/$userId'
    | '/api/cron/payments'
    | '/api/cron/sync-turo'
    | '/_authed/trips/'
    | '/_authed/trips/$bookingId_/extras'
    | '/_authed/trips/$bookingId_/photos'
    | '/_authed/trips/$bookingId_/receipt'
    | '/_authed/trips/$bookingId_/pay/$chargeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRoute
  PoliciesRoute: typeof PoliciesRouteWithChildren
  ReviewsRoute: typeof ReviewsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  FleetCarSlugRoute: typeof FleetCarSlugRoute
  FleetIndexRoute: typeof FleetIndexRoute
  ApiCronPaymentsRoute: typeof ApiCronPaymentsRoute
  ApiCronSyncTuroRoute: typeof ApiCronSyncTuroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet/': {
      id: '/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof FleetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/policies/terms': {
      id: '/policies/terms'
      path: '/terms'
      fullPath: '/policies/terms'
      preLoaderRoute: typeof PoliciesTermsRouteImport
      parentRoute: typeof PoliciesRoute
    }
    '/policies/privacy': {
      id: '/policies/privacy'
      path: '/privacy'
      fullPath: '/policies/privacy'
      preLoaderRoute: typeof PoliciesPrivacyRouteImport
      parentRoute: typeof PoliciesRoute
    }
    '/policies/cancellation': {
      id: '/policies/cancellation'
      path: '/cancellation'
      fullPath: '/policies/cancellation'
      preLoaderRoute: typeof PoliciesCancellationRouteImport
      parentRoute: typeof PoliciesRoute
    }
    '/fleet/$carSlug': {
      id: '/fleet/$carSlug'
      path: '/fleet/$carSlug'
      fullPath: '/fleet/$carSlug'
      preLoaderRoute: typeof FleetCarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trips/': {
      id: '/_authed/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof AuthedTripsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/cron/sync-turo': {
      id: '/api/cron/sync-turo'
      path: '/api/cron/sync-turo'
      fullPath: '/api/cron/sync-turo'
      preLoaderRoute: typeof ApiCronSyncTuroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/payments': {
      id: '/api/cron/payments'
      path: '/api/cron/payments'
      fullPath: '/api/cron/payments'
      preLoaderRoute: typeof ApiCronPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user/$userId': {
      id: '/admin/user/$userId'
      path: '/user/$userId'
      fullPath: '/admin/user/$userId'
      preLoaderRoute: typeof AdminUserUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trips/history': {
      id: '/admin/trips/history'
      path: '/trips/history'
      fullPath: '/admin/trips/history'
      preLoaderRoute: typeof AdminTripsHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trips/booked': {
      id: '/admin/trips/booked'
      path: '/trips/booked'
      fullPath: '/admin/trips/booked'
      preLoaderRoute: typeof AdminTripsBookedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reservation/$bookingId': {
      id: '/admin/reservation/$bookingId'
      path: '/reservation/$bookingId'
      fullPath: '/admin/reservation/$bookingId'
      preLoaderRoute: typeof AdminReservationBookingIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/business/tax-information': {
      id: '/admin/business/tax-information'
      path: '/business/tax-information'
      fullPath: '/admin/business/tax-information'
      preLoaderRoute: typeof AdminBusinessTaxInformationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/business/ratings-reviews': {
      id: '/admin/business/ratings-reviews'
      path: '/business/ratings-reviews'
      fullPath: '/admin/business/ratings-reviews'
      preLoaderRoute: typeof AdminBusinessRatingsReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/business/earnings': {
      id: '/admin/business/earnings'
      path: '/business/earnings'
      fullPath: '/admin/business/earnings'
      preLoaderRoute: typeof AdminBusinessEarningsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authed/trips/$bookingId': {
      id: '/_authed/trips/$bookingId'
      path: '/trips/$bookingId'
      fullPath: '/trips/$bookingId'
      preLoaderRoute: typeof AuthedTripsBookingIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/profile_/edit': {
      id: '/_authed/profile_/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof AuthedProfileEditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/checkout/$carId': {
      id: '/_authed/checkout/$carId'
      path: '/checkout/$carId'
      fullPath: '/checkout/$carId'
      preLoaderRoute: typeof AuthedCheckoutCarIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trips/$bookingId_/receipt': {
      id: '/_authed/trips/$bookingId_/receipt'
      path: '/trips/$bookingId/receipt'
      fullPath: '/trips/$bookingId/receipt'
      preLoaderRoute: typeof AuthedTripsBookingIdReceiptRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trips/$bookingId_/photos': {
      id: '/_authed/trips/$bookingId_/photos'
      path: '/trips/$bookingId/photos'
      fullPath: '/trips/$bookingId/photos'
      preLoaderRoute: typeof AuthedTripsBookingIdPhotosRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trips/$bookingId_/extras': {
      id: '/_authed/trips/$bookingId_/extras'
      path: '/trips/$bookingId/extras'
      fullPath: '/trips/$bookingId/extras'
      preLoaderRoute: typeof AuthedTripsBookingIdExtrasRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/trips/$bookingId_/pay/$chargeId': {
      id: '/_authed/trips/$bookingId_/pay/$chargeId'
      path: '/trips/$bookingId/pay/$chargeId'
      fullPath: '/trips/$bookingId/pay/$chargeId'
      preLoaderRoute: typeof AuthedTripsBookingIdPayChargeIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedCheckoutCarIdRoute: typeof AuthedCheckoutCarIdRoute
  AuthedProfileEditRoute: typeof AuthedProfileEditRoute
  AuthedTripsBookingIdRoute: typeof AuthedTripsBookingIdRoute
  AuthedTripsIndexRoute: typeof AuthedTripsIndexRoute
  AuthedTripsBookingIdExtrasRoute: typeof AuthedTripsBookingIdExtrasRoute
  AuthedTripsBookingIdPhotosRoute: typeof AuthedTripsBookingIdPhotosRoute
  AuthedTripsBookingIdReceiptRoute: typeof AuthedTripsBookingIdReceiptRoute
  AuthedTripsBookingIdPayChargeIdRoute: typeof AuthedTripsBookingIdPayChargeIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedCheckoutCarIdRoute: AuthedCheckoutCarIdRoute,
  AuthedProfileEditRoute: AuthedProfileEditRoute,
  AuthedTripsBookingIdRoute: AuthedTripsBookingIdRoute,
  AuthedTripsIndexRoute: AuthedTripsIndexRoute,
  AuthedTripsBookingIdExtrasRoute: AuthedTripsBookingIdExtrasRoute,
  AuthedTripsBookingIdPhotosRoute: AuthedTripsBookingIdPhotosRoute,
  AuthedTripsBookingIdReceiptRoute: AuthedTripsBookingIdReceiptRoute,
  AuthedTripsBookingIdPayChargeIdRoute: AuthedTripsBookingIdPayChargeIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface AdminRouteChildren {
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBusinessEarningsRoute: typeof AdminBusinessEarningsRoute
  AdminBusinessRatingsReviewsRoute: typeof AdminBusinessRatingsReviewsRoute
  AdminBusinessTaxInformationRoute: typeof AdminBusinessTaxInformationRoute
  AdminReservationBookingIdRoute: typeof AdminReservationBookingIdRoute
  AdminTripsBookedRoute: typeof AdminTripsBookedRoute
  AdminTripsHistoryRoute: typeof AdminTripsHistoryRoute
  AdminUserUserIdRoute: typeof AdminUserUserIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalendarRoute: AdminCalendarRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBusinessEarningsRoute: AdminBusinessEarningsRoute,
  AdminBusinessRatingsReviewsRoute: AdminBusinessRatingsReviewsRoute,
  AdminBusinessTaxInformationRoute: AdminBusinessTaxInformationRoute,
  AdminReservationBookingIdRoute: AdminReservationBookingIdRoute,
  AdminTripsBookedRoute: AdminTripsBookedRoute,
  AdminTripsHistoryRoute: AdminTripsHistoryRoute,
  AdminUserUserIdRoute: AdminUserUserIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PoliciesRouteChildren {
  PoliciesCancellationRoute: typeof PoliciesCancellationRoute
  PoliciesPrivacyRoute: typeof PoliciesPrivacyRoute
  PoliciesTermsRoute: typeof PoliciesTermsRoute
}

const PoliciesRouteChildren: PoliciesRouteChildren = {
  PoliciesCancellationRoute: PoliciesCancellationRoute,
  PoliciesPrivacyRoute: PoliciesPrivacyRoute,
  PoliciesTermsRoute: PoliciesTermsRoute,
}

const PoliciesRouteWithChildren = PoliciesRoute._addFileChildren(
  PoliciesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  MyBookingsRoute: MyBookingsRoute,
  PoliciesRoute: PoliciesRouteWithChildren,
  ReviewsRoute: ReviewsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  FleetCarSlugRoute: FleetCarSlugRoute,
  FleetIndexRoute: FleetIndexRoute,
  ApiCronPaymentsRoute: ApiCronPaymentsRoute,
  ApiCronSyncTuroRoute: ApiCronSyncTuroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
